### ISSUE TITLE
How to pass values via set to extraEnv parameter of helm chart

### ISSUE THREAD

**Issue by aigamdocs** [lablabs/terraform-aws-eks-external-dns#13]
Hi,

I have an issue with passing values to extraEnv parameter of helm chart via set. 

I tried few ways, but with no success. 

Could you please advise how it can be implemented.

Thanks a lot

**Comment by adys** [comment]
Hi @aigamdocs ,

We've prepared a PR where we want to merge an example which should answer your question. Please check the diff and let me know https://github.com/lablabs/terraform-aws-eks-external-dns/pull/14/files

**Comment by adys** [comment]
Addressed in #14
