### ISSUE TITLE
Support TF 0.14.x

### ISSUE THREAD

**Issue by whume** [lablabs/terraform-aws-eks-external-dns#16]
I think I am hitting this bug in the modules due to the use of the dynamic providers but I cannot test to confirm since the modules do not support Terraform 0.14. Can we add support for that?

https://github.com/hashicorp/terraform-provider-helm/issues/476

**Comment by haad** [comment]
Sure if we are open to merge any PR TF 0.14 if you have any time on your hands. Just make sure you bump major version.

**Comment by joaoantunes** [comment]
I've made a fork and pull request to support this. #17 
While this is not available by this branch I've also published that to Terraform repository.
