### ISSUE TITLE
The lablabs/eks-external-dns module 0.9.0 doesn't work on Kubernetes version 1.22

### ISSUE THREAD

**Issue by jon-eicher** [lablabs/terraform-aws-eks-external-dns#26]
After upgrading AWS EKS to version 1.22, the lablabs 0.9.0 external-dns pod goes into a CrashLoopBackOff.  This is caused by k8s 1.22 stopping to support a couple deprecated APIs, including the Ingress in extensions/v1beta1.

Fix is in external-dns version 0.10.0+ :
https://github.com/kubernetes-sigs/external-dns/issues/2168

The external-dns logs show this fatal error:
time="2022-04-15T21:19:09Z" level=fatal msg="failed to sync cache: timed out waiting for the condition"

**Comment by cubiclelord** [comment]
+1

**Comment by dojci** [comment]
Sorry for the late reply, there are multiple ways you can change the version:
* update `helm_chart_version` as needed ([bitnami/external-dns](https://github.com/bitnami/charts/blob/master/bitnami/external-dns/Chart.yaml#L27)) or even use different
* override `appVersion` or `image.tag` in values

Will that solve your problems ?

**Comment by dojci** [comment]
FYI: we just made a [new release](https://github.com/lablabs/terraform-aws-eks-external-dns/releases/tag/v1.0.0) where, among other changes, we upgraded default chart version to the latest release (6.3.0).
