### ISSUE TITLE
Add support for deploying External DNS on existent K8S Namespace in cluster

### ISSUE THREAD

**Issue by gastoncan** [lablabs/terraform-aws-eks-external-dns#3]
I would like to be able to deploy External DNS into an existent K8S namespace in my cluster, such as `kube-dns`, without letting this module to create it for me.
As per actual behavior, the options are to use default `kube-system` or to create a new namespace.
I suggest to create an optional boolean flag (i.e.) `k8s_create_namespace` with default value `true`.
The new flag should be introduced in the `count` field of the `kubernetes_namespace` resource as follows:
```resource "kubernetes_namespace" "external_dns" {
  count = (var.enabled && var.k8s_create_namespace && var.k8s_namespace != "kube-system") ? 1 : 0
  ....
```

**Comment by martinhaus** [comment]
@gastoncan  
Hey, sorry for the delayed response. The change looks good to me. 
Feel free to make a PR for this as well. If not one of us will take a look at implementing this later.
