### ISSUE TITLE
feature: Suppress last_used_date change detection

### ISSUE THREAD

**Issue by evonz-mx** [lablabs/terraform-aws-eks-external-dns#33]
### Summary

It would be nice to add a lifecycle rule to the "aws_iam_role" "this" so that usage doesn't cause change detection notes on every apply.

This appears in almost every Terraform run in our system (which is a dev system, so it experiences a fair amount of application change):

~ role_last_used        = [
          ~ {
              ~ last_used_date = "2023-05-19T13:45:44Z" -> "2023-05-19T15:03:24Z"
                # (1 unchanged attribute hidden)
            },
        ]

### Issue Type

Feature Idea

**Comment by tomas-balaz** [comment]
Hi @evonz-mx, thank you for your suggestion.

But I don't think that your idea can be materialized - according to these resources:
- https://support.hashicorp.com/hc/en-us/articles/4405950960147-New-Feature-Objects-have-changed-outside-of-Terraform-
- https://github.com/hashicorp/terraform/issues/28803#issuecomment-951209299
