### ISSUE TITLE
bug: argo_helm_values not working

### ISSUE THREAD

**Issue by babebort** [lablabs/terraform-aws-eks-external-dns#34]
### Summary

after providing argo_helm_values deployments args is not changed.

### Issue Type

Bug Report

### Terraform Version

```console
% terraform --version 
Terraform v1.4.3-dev
on darwin_amd64
+ provider registry.terraform.io/cloudposse/utils v1.5.0
+ provider registry.terraform.io/hashicorp/aws v4.40.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/random v3.4.3

Your version of Terraform is out of date! The latest version
is 1.4.6. You can update by downloading from https://www.terraform.io/downloads.html
```

### Steps to Reproduce

```hcl (paste below)
locals {
  external_dns_values = templatefile("./helm-values/external-dns.yaml", {})
}


module "argo_external_dns" {
  enabled           = true
  argo_enabled      = true
  argo_helm_enabled = true
  ....
  argo_helm_values =  local.external_dns_values
}

./helm-values/external-dns.yaml contains

`global:
  imageRegistry: docker.io

nodeSelector:
  node-group-purpose: infra

policy: sync
logLevel: debug
triggerLoopOnEvent: true
interval: 5s

cloudflare:
  proxied: true
  secretName: cloudflare

#env:
#  - name: CF_API_TOKEN
#    valueFrom:
#      secretKeyRef:
#        name: cloudflare
#        key: CF_API_TOKEN

domainFilters: ["google.com"]
#zoneIdFilters: ["1c5106c2b6c6c329ce0acc3bff85380b"]



resources:
  limits:
    memory: 100Mi
    cpu: 100m
  requests:
    memory: 50Mi
    cpu: 50m

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 60s
    scrapeTimeout: 10s
`
```

### Expected Results

As I passed external-dns.yaml, deployment arguments should be applied, but it is the default:

`
      containers:
        - args:
            - '--metrics-address=:7979'
            - '--log-level=info'
            - '--log-format=text'
            - '--policy=upsert-only'
            - '--provider=aws'
            - '--registry=txt'
            - '--interval=1m'
            - '--source=service'
            - '--source=ingress'
            - '--aws-api-retries=3'
            - '--aws-zone-type='
            - '--aws-batch-change-size=1000'
            - `

### Actual Results

```console
Apply complete! Resources: 9 added,
```

**Comment by tomas-balaz** [comment]
Hi @babebort 

Your template file `./helm-values/external-dns.yaml` contains values for the external DNS helm chart. Variable `argo_helm_values` contains values for the helm chart deploying the _argo application resource_ (defined in the [local helm chart](https://github.com/lablabs/terraform-aws-eks-external-dns/tree/master/helm/argocd-application)) to override the default setting of the Argo application.

You should use `values` variable rather than `argo_helm_values` to pass custom values to the external DNS helm chart

```terraform
locals {
  external_dns_values = templatefile("./helm-values/external-dns.yaml", {})
}

module "argo_external_dns" {
  enabled           = true
  argo_enabled      = true
  argo_helm_enabled = true
  ....
  values =  local.external_dns_values
}
```

**Comment by babebort** [comment]
@tomas-balaz I am very grateful to you, it really makes sense. Hope it will help to somebody else.
