### ISSUE TITLE
Add support for configuring the External DNS policy

### ISSUE THREAD

**Issue by gastoncan** [lablabs/terraform-aws-eks-external-dns#4]
Hi;
I would like to be able to configure the External DNS "policy" argument (as per [Setup Guide](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/aws.md)), to be able to set "upset-only" or "sync" values.

Enable full sync - [https://github.com/kubernetes-sigs/external-dns/issues/442](https://github.com/kubernetes-sigs/external-dns/issues/442)

Required changes:

values.yaml.tpl
```
## Modify how DNS records are sychronized between sources and providers (options: sync, upsert-only)
##
policy: ${ policy }
```

main.tf
```
resource "helm_release" "external_dns" {
...
  values = [
    "${templatefile("${path.module}/templates/values.yaml.tpl",
      {
        "cluster_name"              = var.cluster_name,
        ...
        "policy"                    = var.policy
      })
    }"
  ]
}
```

variables.tf
```
variable "policy" {
  default     = "upsert-only"
  description = "Policy for creating or updating records. Possible values: \"sync\" - allows for full synchronization of DNS records or \"upsert-only\" - allows evrything but deleting DNS records."
}
```

**Comment by adys** [comment]
@gastoncan the proposed changes look good. Could you open a PR?

**Comment by gastoncan** [comment]
Thanks @toabi and @adys for that!
